---
version: '3.9'
services:
  postgres:
    image: postgres:12.5
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  traefik:
    image: traefik:v1.7.26-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --logLevel=ERROR
      --api.dashboard
      --docker
      --entrypoints="Name:http Address::80"
      --defaultentrypoints="http"
    ports:
      - 80:80
      - 3000:8080
  keycloak:
    image: jboss/keycloak:11.0.3
    deploy:
      replicas: 3
    environment:
      CONFIGURATION: standalone-ha.xml
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm.json
      # KEYCLOAK_LOGLEVEL: DEBUG
      # KEYCLOAK_STATISTICS: all
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      JGROUPS_DISCOVERY_PROPERTIES: datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=500,initialize_sql="CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"
      CACHE_OWNERS_COUNT: 2
      CACHE_OWNERS_AUTH_SESSIONS_COUNT: 2
    command: >-
      -b 0.0.0.0 -bmanagement 0.0.0.0
    volumes:
      - ./realm.json:/tmp/realm.json
      - /tmp/:/tmp/
    labels:
      traefik.enable: true
      traefik.keycloak.port: 8080
      traefik.keycloak.protocol: http
      traefik.keycloak.frontend.rule: Host:localhost
      traefik.wildfly.port: 9990
      traefik.wildfly.protocol: http
      traefik.wildfly.frontend.rule: Host:localhost
    depends_on:
      - postgres
